spring:
  application:
    name: restful-web-services
  banner:
    location: classpath:banner/banner.txt

server:
  port: 0

logging:
  level:
    org:
      springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"